# Generated by Django 4.0.3 on 2022-05-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajana_mehdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='traitement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='rendezvous',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ajana_mehdi.rendezvous'),
        ),
    ]
